version: '2.1'

services:
  #mongodb:
  #  image: mongo
  #  container_name: mongodb
  #  ports:
  #    - "27017:27017"
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      -  "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_db_pass
      MYSQL_DATABASE: django_db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
  esameld:
    image: esameld
    container_name: esameld
    command: [sh, docker-startup.sh] #python3 manage.py runserver 0.0.0.0:8000
    build: .
    environment:
      - MONGO_URI=mongodb
      - MYSQL_URI=mysql_db
    ports:
      - "8000:8000"
    links:
      - mysql_db
    #  - mongodb
    depends_on:
      mysql_db:
        condition: service_healthy