# Generated by Django 2.0.5 on 2018-06-30 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('drivers', '0001_initial'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.PositiveIntegerField(default=0)),
                ('startDateTime', models.DateTimeField(auto_now_add=True)),
                ('endDateTime', models.DateTimeField(auto_now_add=True)),
                ('refound_request', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver')),
                ('endPos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endPos', to='map.PosLatLng')),
                ('startPos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startPos', to='map.PosLatLng')),
            ],
        ),
    ]
