# Generated by Django 2.0.5 on 2018-07-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('map', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(default=0)),
                ('start_date_time', models.DateTimeField(blank=True)),
                ('end_date_time', models.DateTimeField(blank=True)),
                ('refound_request', models.BooleanField(default=False)),
                ('driver_reported', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Client')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drivers.Driver')),
                ('end_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endPos', to='map.PosLatLng')),
                ('start_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startPos', to='map.PosLatLng')),
            ],
        ),
    ]
