# Generated by Django 2.0.5 on 2018-07-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='fee',
            field=models.FloatField(default=0),
        ),
    ]
