# Generated by Django 2.0.5 on 2018-07-05 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20180705_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drivers.Driver'),
        ),
    ]
