# Generated by Django 2.0.5 on 2018-06-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosLatLng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.PositiveSmallIntegerField()),
                ('lng', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
