# Generated by Django 2.0.5 on 2018-07-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poslatlng',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='poslatlng',
            name='lng',
            field=models.FloatField(),
        ),
    ]
