# Generated by Django 2.0.5 on 2018-06-30 14:44

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('userbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.UserBase')),
                ('driver_rate_per_km', models.PositiveIntegerField(default=0)),
                ('driver_max_distance', models.PositiveIntegerField(default=0)),
                ('driver_common_start_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.PosLatLng')),
            ],
            options={
                'permissions': (('driver', 'DRIVER'),),
            },
            bases=('authentication.userbase',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TimeAvail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(default=datetime.datetime(2018, 6, 30, 16, 44, 26, 214755), max_length=5)),
                ('duration', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_time_avail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.TimeAvail'),
        ),
    ]
