# Generated by Django 2.0.5 on 2018-07-22 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('travels', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='clients',
            field=models.ManyToManyField(through='travels.Travel', to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='timeavail',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2018, 7, 22, 17, 10, 6, 273621), max_length=5),
        ),
    ]
