# Generated by Django 2.0.5 on 2018-07-12 23:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='common_start_pos_lat',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='common_start_pos_lng',
        ),
        migrations.AddField(
            model_name='driver',
            name='common_start_pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.PosLatLng'),
        ),
        migrations.AlterField(
            model_name='timeavail',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2018, 7, 13, 1, 34, 20, 867356), max_length=5),
        ),
    ]
