# Generated by Django 2.0.5 on 2018-06-30 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeavail',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2018, 6, 30, 17, 15, 22, 703937), max_length=5),
        ),
    ]
