# Generated by Django 2.0.5 on 2018-06-30 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20180630_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeavail',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2018, 6, 30, 17, 44, 12, 590013), max_length=5),
        ),
    ]
