# Generated by Django 2.0.5 on 2018-07-04 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20180704_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='common_start_pos_lat',
            field=models.FloatField(default=41.98),
        ),
        migrations.AlterField(
            model_name='driver',
            name='common_start_pos_lng',
            field=models.FloatField(default=12.5),
        ),
        migrations.AlterField(
            model_name='driver',
            name='max_distance',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rate_per_km',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='timeavail',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2018, 7, 5, 0, 49, 35, 744634), max_length=5),
        ),
    ]
