# Generated by Django 2.0.5 on 2018-07-22 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20180722_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='max_distance',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rate_per_km',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='timeavail',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2018, 7, 22, 22, 19, 58, 414112), max_length=5),
        ),
    ]
