# Generated by Django 2.0.5 on 2018-07-05 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20180705_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeavail',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2018, 7, 5, 21, 19, 22, 433775), max_length=5),
        ),
    ]
