# Generated by Django 2.0.5 on 2018-07-05 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20180705_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeavail',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2018, 7, 5, 23, 13, 2, 29999), max_length=5),
        ),
    ]
