# Generated by Django 2.0.5 on 2018-07-25 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20180725_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeavail',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2018, 7, 25, 18, 22, 44, 578840), max_length=5),
        ),
    ]
