# Generated by Django 2.0.5 on 2018-07-05 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20180705_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='reports',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeavail',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2018, 7, 6, 0, 41, 45, 594249), max_length=5),
        ),
    ]
